use crate::content::{ConstDecodedRow, Row};
use crate::values::{ConstValue, Schema};

pub mod obj;

pub static ROWS: [Row; 88] = [
    // Object "Tag"
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Unit),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::TAG_SCHEMA),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG,
        obj::TAG_INFERRED,
        ConstValue::Unit,
    )),
    // Object "Tag.Schema"
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_SCHEMA,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Schema),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_SCHEMA,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_SCHEMA,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    // Object "Tag.Parent"
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_PARENT,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::ObjectReference(Some(obj::TAG))),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_PARENT,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_PARENT,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    // Object "Tag.Constraint"
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_CONSTRAINT,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::ObjectReference(Some(obj::CONSTRAINT))),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_CONSTRAINT,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_CONSTRAINT,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_CONSTRAINT,
        obj::TAG_UNIQUE_ID,
        ConstValue::Unit,
    )),
    // Object "Tag.Inferred"
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_INFERRED,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Unit),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_INFERRED,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_INFERRED,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    // Object "Tag.UniqueId"
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_UNIQUE_ID,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Unit),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_UNIQUE_ID,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_UNIQUE_ID,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::_CO_HAS_TAG_AND_NOT_INFERRED),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_UNIQUE_ID,
        obj::TAG_UNIQUE_ID,
        ConstValue::Unit,
    )),
    // Object "Tag.UniqueValue"
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_UNIQUE_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Unit),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_UNIQUE_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::ObjectReference(None)),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_UNIQUE_VALUE,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_UNIQUE_VALUE,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::_CO_HAS_TAG_AND_NOT_INFERRED),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::TAG_UNIQUE_VALUE,
        obj::TAG_UNIQUE_ID,
        ConstValue::Unit,
    )),
    // Object "Tag.Constraint"
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Unit),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::_CO_CONSTRAINT),
    )),
    // Object "Constraint.Or"
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_OR,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::ObjectReference(Some(obj::CONSTRAINT))),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_OR,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_OR,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    // Object "Constraint.And"
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_AND,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::ObjectReference(Some(obj::CONSTRAINT))),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_AND,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_AND,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    // Object "Constraint.OrNot"
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_OR_NOT,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::ObjectReference(Some(obj::CONSTRAINT))),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_OR_NOT,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_OR_NOT,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    // Object "Constraint.AndNot"
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_AND_NOT,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::ObjectReference(Some(obj::CONSTRAINT))),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_AND_NOT,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_AND_NOT,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    // Object "Constraint.Tag"
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_TAG,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::ObjectReference(Some(obj::TAG))),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_TAG,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_TAG,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_TAG,
        obj::TAG_UNIQUE_ID,
        ConstValue::Unit,
    )),
    // Object `CONSTRAINT_WITH_VALUE`
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Unit),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Integer),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Float),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Character),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Duration),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::DateTime),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::ObjectReference(None)),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Schema),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Language),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Url),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Color),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Email),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Text),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Binary),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_SCHEMA,
        ConstValue::Schema(Schema::Encrypted),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_PARENT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_CONSTRAINT,
        ConstValue::ObjectReference(obj::CONSTRAINT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::CONSTRAINT_WITH_VALUE,
        obj::TAG_UNIQUE_ID,
        ConstValue::Unit,
    )),
    // Object `_CO_HAS_TAG_AND_NOT_INFERRED`
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_HAS_TAG_AND_NOT_INFERRED,
        obj::CONSTRAINT_AND,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_HAS_TAG_AND_NOT_INFERRED,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::TAG_INFERRED),
    )),
    // Object `_CO_CONSTRAINT`
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CONSTRAINT,
        obj::CONSTRAINT_OR,
        ConstValue::ObjectReference(obj::_CO_CV_TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CONSTRAINT,
        obj::CONSTRAINT_OR,
        ConstValue::ObjectReference(obj::_CO_CV_TAG_WITH_VALUE),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CONSTRAINT,
        obj::CONSTRAINT_OR,
        ConstValue::ObjectReference(obj::_CO_CV_ORS),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CONSTRAINT,
        obj::CONSTRAINT_OR,
        ConstValue::ObjectReference(obj::_CO_CV_ANDS),
    )),
    // Object `_CO_CV_TAG`
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_TAG,
        obj::CONSTRAINT_AND,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_TAG,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::CONSTRAINT_TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_TAG,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::_CO_OR_OR_OR_NOT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_TAG,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::_CO_AND_OR_AND_NOT),
    )),
    // Object `_CO_CV_TAG_WITH_VALUE`
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_TAG_WITH_VALUE,
        obj::CONSTRAINT_AND,
        ConstValue::ObjectReference(obj::CONSTRAINT_TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_TAG_WITH_VALUE,
        obj::CONSTRAINT_AND,
        ConstValue::ObjectReference(obj::CONSTRAINT_WITH_VALUE),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_TAG_WITH_VALUE,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::CONSTRAINT_TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_TAG_WITH_VALUE,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::_CO_OR_OR_OR_NOT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_TAG_WITH_VALUE,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::_CO_AND_OR_AND_NOT),
    )),
    // Object `_CO_CV_ORS`
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_ORS,
        obj::CONSTRAINT_AND,
        ConstValue::ObjectReference(obj::_CO_OR_OR_OR_NOT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_ORS,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_ORS,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::_CO_AND_OR_AND_NOT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_ORS,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::CONSTRAINT_TAG),
    )),
    // Object `_CO_CV_ANDS`
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_ANDS,
        obj::CONSTRAINT_AND,
        ConstValue::ObjectReference(obj::_CO_AND_OR_AND_NOT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_ANDS,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::TAG),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_ANDS,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::_CO_OR_OR_OR_NOT),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_CV_ANDS,
        obj::CONSTRAINT_AND_NOT,
        ConstValue::ObjectReference(obj::CONSTRAINT_TAG),
    )),
    // Object `_CO_OR_OR_OR_NOT`
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_OR_OR_OR_NOT,
        obj::CONSTRAINT_OR,
        ConstValue::ObjectReference(obj::CONSTRAINT_OR),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_OR_OR_OR_NOT,
        obj::CONSTRAINT_OR,
        ConstValue::ObjectReference(obj::CONSTRAINT_OR_NOT),
    )),
    // Object `_CO_AND_OR_AND_NOT`
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_AND_OR_AND_NOT,
        obj::CONSTRAINT_OR,
        ConstValue::ObjectReference(obj::CONSTRAINT_AND),
    )),
    Row::const_encode(ConstDecodedRow::Association(
        obj::_CO_AND_OR_AND_NOT,
        obj::CONSTRAINT_OR,
        ConstValue::ObjectReference(obj::CONSTRAINT_AND_NOT),
    )),
];
