import {ObjectId} from "./model.ts";

export const MIN_OBJECT_ID = 1024;

export const BUILT_IN_TAG_ID_LAST_READ = 32;
export const BUILT_IN_TAG_ID_LAST_WRITTEN = 33;
export const BUILT_IN_TAG_ID_CREATED = 34;
export const BUILT_IN_TAG_ID_SHA_256 = 35;
export const BUILT_IN_TAG_ID_OWNER = 36;
export const BUILT_IN_TAG_ID_FILE_TYPE = 37;
export const BUILT_IN_TAG_ID_SOURCE = 38;
export const BUILT_IN_TAG_ID_TEMPORARY = 39;
export const BUILT_IN_TAG_ID_ENTRY = 40;
export const BUILT_IN_TAG_ID_AUTHOR = 41;
export const BUILT_IN_TAG_ID_SIZE = 42;
export const BUILT_IN_TAG_ID_TAG = 43;
export const BUILT_IN_TAG_ID_FILE_COUNT = 44;
export const BUILT_IN_TAG_ID_DIRECTORY_COUNT = 45;
export const BUILT_IN_TAG_ID_TOTAL_FILE_COUNT = 46;
export const BUILT_IN_TAG_ID_TOTAL_DIRECTORY_COUNT = 47;
export const BUILT_IN_TAG_ID_TRASHED = 48;
export const BUILT_IN_TAG_ID_FILE = 49;
export const BUILT_IN_TAG_ID_DIRECTORY = 50;
export const BUILT_IN_TAG_ID_FAVOURITE = 51;
export const BUILT_IN_TAG_ID_IMAGE = 52;
export const BUILT_IN_TAG_ID_IMAGE_WIDTH = 53;
export const BUILT_IN_TAG_ID_IMAGE_HEIGHT = 54;
// ...
export const BUILT_IN_TAG_ID_TITLE = 62;
export const BUILT_IN_TAG_ID_PATH = 63;
export const BUILT_IN_TAG_ID_TEXT = 64;
export const BUILT_IN_TAG_ID_TEXT_WORD_COUNT = 65;
export const BUILT_IN_TAG_ID_FILE_TYPE_EXTENSION = 66;
export const BUILT_IN_TAG_ID_FILE_TYPE_INNER = 67;
export const BUILT_IN_TAG_ID_ENTRY_NAME = 68;
export const BUILT_IN_TAG_ID_ENTRY_PARENT = 69;
export const BUILT_IN_TAG_ID_READ_ACCESS = 70;
export const BUILT_IN_TAG_ID_WRITE_ACCESS = 71;
export const BUILT_IN_TAG_ID_USER = 72;
export const BUILT_IN_TAG_ID_GROUP = 73;
export const BUILT_IN_TAG_ID_TAG_SCHEMA = 74;
export const BUILT_IN_TAG_ID_TAG_PARENT = 75;
export const BUILT_IN_TAG_ID_TAG_NAME = 76;
export const BUILT_IN_TAG_ID_TAG_TRANSLATION = 77;
export const BUILT_IN_TAG_ID_TAG_TRANSLATION_LANGUAGE = 78;
export const BUILT_IN_TAG_ID_TAG_TRANSLATION_NAME = 79;

export const isBuiltInTagId = (tagId: ObjectId): tagId is BuiltInTagId =>
    32 <= tagId && tagId <= 80;

export type BuiltInTagId = typeof BUILT_IN_TAG_ID_LAST_READ
    | typeof BUILT_IN_TAG_ID_LAST_WRITTEN
    | typeof BUILT_IN_TAG_ID_CREATED
    | typeof BUILT_IN_TAG_ID_SHA_256
    | typeof BUILT_IN_TAG_ID_OWNER
    | typeof BUILT_IN_TAG_ID_FILE_TYPE
    | typeof BUILT_IN_TAG_ID_SOURCE
    | typeof BUILT_IN_TAG_ID_TEMPORARY
    | typeof BUILT_IN_TAG_ID_ENTRY
    | typeof BUILT_IN_TAG_ID_AUTHOR
    | typeof BUILT_IN_TAG_ID_SIZE
    | typeof BUILT_IN_TAG_ID_TAG
    | typeof BUILT_IN_TAG_ID_FILE_COUNT
    | typeof BUILT_IN_TAG_ID_DIRECTORY_COUNT
    | typeof BUILT_IN_TAG_ID_TOTAL_FILE_COUNT
    | typeof BUILT_IN_TAG_ID_TOTAL_DIRECTORY_COUNT
    | typeof BUILT_IN_TAG_ID_TRASHED
    | typeof BUILT_IN_TAG_ID_FILE
    | typeof BUILT_IN_TAG_ID_DIRECTORY
    | typeof BUILT_IN_TAG_ID_FAVOURITE
    | typeof BUILT_IN_TAG_ID_IMAGE
    | typeof BUILT_IN_TAG_ID_IMAGE_WIDTH
    | typeof BUILT_IN_TAG_ID_IMAGE_HEIGHT
    | typeof BUILT_IN_TAG_ID_TITLE
    | typeof BUILT_IN_TAG_ID_PATH
    | typeof BUILT_IN_TAG_ID_TEXT
    | typeof BUILT_IN_TAG_ID_TEXT_WORD_COUNT
    | typeof BUILT_IN_TAG_ID_FILE_TYPE_EXTENSION
    | typeof BUILT_IN_TAG_ID_FILE_TYPE_INNER
    | typeof BUILT_IN_TAG_ID_ENTRY_NAME
    | typeof BUILT_IN_TAG_ID_ENTRY_PARENT
    | typeof BUILT_IN_TAG_ID_READ_ACCESS
    | typeof BUILT_IN_TAG_ID_WRITE_ACCESS
    | typeof BUILT_IN_TAG_ID_USER
    | typeof BUILT_IN_TAG_ID_GROUP
    | typeof BUILT_IN_TAG_ID_TAG_SCHEMA
    | typeof BUILT_IN_TAG_ID_TAG_PARENT
    | typeof BUILT_IN_TAG_ID_TAG_NAME
    | typeof BUILT_IN_TAG_ID_TAG_TRANSLATION
    | typeof BUILT_IN_TAG_ID_TAG_TRANSLATION_LANGUAGE
    | typeof BUILT_IN_TAG_ID_TAG_TRANSLATION_NAME

export const BUILT_IN_TAG_PARENTS: Partial<Record<BuiltInTagId, BuiltInTagId>> = {
    [BUILT_IN_TAG_ID_FILE_TYPE]: BUILT_IN_TAG_ID_FILE,
    [BUILT_IN_TAG_ID_IMAGE_WIDTH]: BUILT_IN_TAG_ID_IMAGE,
    [BUILT_IN_TAG_ID_IMAGE_HEIGHT]: BUILT_IN_TAG_ID_IMAGE,
    [BUILT_IN_TAG_ID_TEXT_WORD_COUNT]: BUILT_IN_TAG_ID_TEXT,
    [BUILT_IN_TAG_ID_FILE_TYPE_EXTENSION]: BUILT_IN_TAG_ID_FILE_TYPE,
    [BUILT_IN_TAG_ID_FILE_TYPE_INNER]: BUILT_IN_TAG_ID_FILE_TYPE,
    [BUILT_IN_TAG_ID_ENTRY_NAME]: BUILT_IN_TAG_ID_ENTRY,
    [BUILT_IN_TAG_ID_ENTRY_PARENT]: BUILT_IN_TAG_ID_ENTRY,
    [BUILT_IN_TAG_ID_TAG_SCHEMA]: BUILT_IN_TAG_ID_TAG,
    [BUILT_IN_TAG_ID_TAG_PARENT]: BUILT_IN_TAG_ID_TAG,
    [BUILT_IN_TAG_ID_TAG_NAME]: BUILT_IN_TAG_ID_TAG,
    [BUILT_IN_TAG_ID_TAG_TRANSLATION]: BUILT_IN_TAG_ID_TAG,
    [BUILT_IN_TAG_ID_TAG_TRANSLATION_NAME]: BUILT_IN_TAG_ID_TAG_TRANSLATION,
    [BUILT_IN_TAG_ID_TAG_TRANSLATION_LANGUAGE]: BUILT_IN_TAG_ID_TAG_TRANSLATION,
};