export const EVENT_OBJECT_DELETE = 1;

export const RPC_OBJECTS_QUERY = 1;
export const RPC_OBJECTS_CREATE = 2;
export const RPC_OBJECTS_EXISTS = 3;

/**
 * Length of the session id in bytes.
 */
export const SESSION_ID_LENGTH = 32;

export const PL_ADMIN = 5;
export const PL_USER = 4;
export const PL_GUEST = 3;

/**
 * The minimum temporary pending id generated by the client.
 */
export const MIN_TEMP_PENDING_ID = 2 ** 10;

export const VL_OBJECT_ID = 1;
export const VL_DECIMAL = 2;
export const VL_INTEGER = 3;
export const VL_STRING = 4;
export const VL_DURATION = 5;
export const VL_DATE_TIME = 6;
export const VL_BOOLEAN = 7;
export const VL_CHARACTER = 8;
export const VL_URL = 9;
export const VL_BINARY = 10;
export const VL_COLOR = 11;
export const VL_EMAIL = 12;

export type EventId = typeof EVENT_OBJECT_DELETE;
export type RPCId = typeof RPC_OBJECTS_EXISTS
    | typeof RPC_OBJECTS_CREATE
    | typeof RPC_OBJECTS_QUERY;

export type ObjectId = number;

export type PermissionLevel = typeof PL_GUEST | typeof PL_USER | typeof PL_ADMIN;

export type Value = {_: typeof VL_OBJECT_ID, v: ObjectId}
    | {_: typeof VL_DECIMAL, v: number}
    | {_: typeof VL_INTEGER, v: number}
    | {_: typeof VL_STRING, v: string}
    | {_: typeof VL_DURATION, v: number}
    | {_: typeof VL_DATE_TIME, v: number}
    | {_: typeof VL_BOOLEAN, v: boolean}
    | {_: typeof VL_CHARACTER, v: number}
    | {_: typeof VL_URL, v: string}
    | {_: typeof VL_BINARY, v: Uint8Array}
    | {_: typeof VL_COLOR, v: string}
    | {_: typeof VL_EMAIL, v: string};