use std::sync::LazyLock;

use everything::ext::AbstractExt;
use everything_structures::{Abstract, Object};

pub const NAMES: LazyLock<[(&'static str, Object); 58]> = LazyLock::new(|| {
    [
        ("ZERO", Abstract::ZERO.into()),
        ("SUCCESSOR_OF", Abstract::SUCCESSOR_OF.into()),
        ("PREDECESSOR_OF", Abstract::PREDECESSOR_OF.into()),
        ("LIST_ITEM", Abstract::LIST_ITEM.into()),
        ("LIST_TAIL", Abstract::LIST_TAIL.into()),
        ("CODE_POINT", Abstract::CODE_POINT.into()),
        ("BIT_0", Abstract::BIT_0.into()),
        ("BIT_1", Abstract::BIT_1.into()),
        ("BIT_SLOT_0", Abstract::BIT_SLOT_0.into()),
        ("BIT_SLOT_1", Abstract::BIT_SLOT_1.into()),
        ("BIT_SLOT_2", Abstract::BIT_SLOT_2.into()),
        ("BIT_SLOT_3", Abstract::BIT_SLOT_3.into()),
        ("BIT_SLOT_4", Abstract::BIT_SLOT_4.into()),
        ("BIT_SLOT_5", Abstract::BIT_SLOT_5.into()),
        ("BIT_SLOT_6", Abstract::BIT_SLOT_6.into()),
        ("BIT_SLOT_7", Abstract::BIT_SLOT_7.into()),
        ("CONTAINS", Abstract::CONTAINS.into()),
        ("AXIOMATIC", Abstract::AXIOMATIC.into()),
        ("FUNCTION", Abstract::FUNCTION.into()),
        ("STATEMENT_SUBJECT", Abstract::STATEMENT_SUBJECT.into()),
        ("STATEMENT_TAG", Abstract::STATEMENT_TAG.into()),
        ("STATEMENT_VALUE", Abstract::STATEMENT_VALUE.into()),
        ("KNOWLEDGE", Abstract::KNOWLEDGE.into()),
        ("NODE_LITERAL", Abstract::NODE_LITERAL.into()),
        ("NODE_AND_LEFT", Abstract::NODE_AND_LEFT.into()),
        ("NODE_AND_RIGHT", Abstract::NODE_AND_RIGHT.into()),
        ("NODE_PARAMETER", Abstract::NODE_PARAMETER.into()),
        ("NODE_COUNT", Abstract::NODE_COUNT.into()),
        ("NODE_QUERY", Abstract::NODE_QUERY.into()),
        ("NODE_EQUAL_LEFT", Abstract::NODE_EQUAL_LEFT.into()),
        ("NODE_EQUAL_RIGHT", Abstract::NODE_EQUAL_RIGHT.into()),
        ("NODE_OR_LEFT", Abstract::NODE_OR_LEFT.into()),
        ("NODE_OR_RIGHT", Abstract::NODE_OR_RIGHT.into()),
        ("NODE_XOR_LEFT", Abstract::NODE_XOR_LEFT.into()),
        ("NODE_XOR_RIGHT", Abstract::NODE_XOR_RIGHT.into()),
        ("NODE_NOT", Abstract::NODE_NOT.into()),
        ("NODE_FUNCTION_SELF", Abstract::NODE_FUNCTION_SELF.into()),
        ("NODE_ADD_LEFT", Abstract::NODE_ADD_LEFT.into()),
        ("NODE_ADD_RIGHT", Abstract::NODE_ADD_RIGHT.into()),
        ("NODE_UNION_LEFT", Abstract::NODE_UNION_LEFT.into()),
        ("NODE_UNION_RIGHT", Abstract::NODE_UNION_RIGHT.into()),
        ("NODE_MAP_SET", Abstract::NODE_MAP_SET.into()),
        ("NODE_MAP_MAPPER", Abstract::NODE_MAP_MAPPER.into()),
        ("NODE_FILTER_SET", Abstract::NODE_FILTER_SET.into()),
        ("NODE_FILTER_FILTER", Abstract::NODE_FILTER_FILTER.into()),
        ("NODE_LESS_LEFT", Abstract::NODE_LESS_LEFT.into()),
        ("NODE_LESS_RIGHT", Abstract::NODE_LESS_RIGHT.into()),
        ("NODE_IF_CONDITION", Abstract::NODE_IF_CONDITION.into()),
        ("NODE_IF_THEN", Abstract::NODE_IF_THEN.into()),
        ("NODE_IF_ELSE", Abstract::NODE_IF_ELSE.into()),
        ("ARITHMETIC_OVERFLOW", Abstract::ARITHMETIC_OVERFLOW.into()),
        ("UNDEFINED", Abstract::UNDEFINED.into()),
        ("NODE_UNWRAP_OR_SET", Abstract::NODE_UNWRAP_OR_SET.into()),
        (
            "NODE_UNWRAP_OR_DEFAULT",
            Abstract::NODE_UNWRAP_OR_DEFAULT.into(),
        ),
        ("NODE_MULTIPLY_LEFT", Abstract::NODE_MULTIPLY_LEFT.into()),
        ("NODE_MULTIPLY_RIGHT", Abstract::NODE_MULTIPLY_RIGHT.into()),
        ("NODE_CALL_CALLEE", Abstract::NODE_CALL_CALLEE.into()),
        ("NODE_CALL_WITH", Abstract::NODE_CALL_WITH.into()),
    ]
});

// {($FUNCTION, {($NODE_EQUAL_LEFT, 1), ($NODE_EQUAL_RIGHT, {($NODE_COUNT, {($NODE_QUERY, {($STATEMENT_SUBJECT, {($NODE_PARAMETER, $ZERO)}), ($STATEMENT_TAG, $AXIOMATIC)})})})})}
