use everything_structures::{Object, Property, Structure};

use crate::{
    ext::{ObjectExt, PropertyExt},
    query::{QuerySubjectsAxiomatically, QueryValuesAxiomatically},
};

/// Represents an object which is either precomputed ([`LazyObject::Eager`])
/// or whose set values are lazily generated by an iterator ([`LazyObject::LazySetValues`]).
#[derive(Clone, Debug)]
pub enum LazyObject {
    Eager(Object),

    /// An iterator over all set values.
    LazySetValues(LazySetValues),
}

impl From<Object> for LazyObject {
    fn from(value: Object) -> Self {
        Self::Eager(value)
    }
}

impl From<LazySetValues> for LazyObject {
    fn from(value: LazySetValues) -> Self {
        Self::LazySetValues(value)
    }
}

/*
impl std::fmt::Debug for LazyObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Eager(object) => object.fmt(f),
            Self::LazySetValues(iter) => f
                .debug_set()
                .entries(iter.clone().map(Property::new_contains))
                .finish(),
        }
    }
}
 */

impl LazyObject {
    /// Interprets the [`Self::AxiomaticQueryValues`] variant as an iterator
    /// over the set items and returns an iterator over set items.
    #[inline]
    pub fn set_values(&self, knowledge: &Structure) -> LazySetValues {
        match self {
            Self::LazySetValues(values) => values.clone(),
            Self::Eager(eager) => LazySetValues::ValuesAxiomatically(eager.set_values(knowledge)),
        }
    }

    pub fn into_set(self) -> Object {
        match self {
            Self::Eager(object) => object,
            Self::LazySetValues(iterator) => iterator.collect_to_set().into(),
        }
    }

    pub fn is_truthy(&mut self, knowledge: &Structure) -> bool {
        match self {
            LazyObject::Eager(object) => object.is_truthy(knowledge),
            LazyObject::LazySetValues(iter) => iter.next().is_some(),
        }
    }
}

#[derive(Debug, Clone)]
pub enum LazySetValues {
    /// Iterator over values of an object.
    ValuesAxiomatically(QueryValuesAxiomatically),

    /// Chains two iterators.
    Union {
        left: Box<LazySetValues>,
        right: Box<LazySetValues>,
    },

    SubjectsAxiomatically(QuerySubjectsAxiomatically),
}

impl LazySetValues {
    pub fn collect_to_set(self) -> Structure {
        let mut properties: Vec<_> = self.map(Property::new_contains).collect();
        Structure::new(&mut properties)
    }

    /// Counts the (remaining) set values of this iterator.
    /// It dedups
    pub fn correct_count(self) -> usize {
        match self {
            LazySetValues::ValuesAxiomatically(axiomatic_query_values) => {
                axiomatic_query_values.count()
            }
            iterator => {
                // This is expensive, no?
                let mut vec = iterator.collect::<Vec<_>>();
                vec.partition_dedup().0.len()
            }
        }
    }
}

impl Iterator for LazySetValues {
    type Item = Object;

    fn next(&mut self) -> Option<Self::Item> {
        match self {
            Self::ValuesAxiomatically(values) => values.next(),
            Self::Union { left, right } => left.next().or_else(|| right.next()),
            Self::SubjectsAxiomatically(subjects) => subjects.next(),
        }
    }
}
