use std::array;

use everything_structures::{Object, Property, Structure};

use crate::{
    ctx::EvaluationContext,
    ext::{ObjectExt, PropertyExt},
    query::{
        QuerySubjectsAndValuesAxiomatically, QuerySubjectsAxiomatically, QueryValuesAxiomatically,
        SubjectAndValue,
    },
};

/// Represents an object which is either precomputed ([`LazyObject::Eager`])
/// or whose set values are lazily generated by an iterator ([`LazyObject::LazySetValues`]).
#[derive(Clone)]
pub enum LazyObject {
    Eager(Object),

    /// An iterator over all set values.
    LazySetValues(LazySetValues),
}

impl From<Object> for LazyObject {
    fn from(value: Object) -> Self {
        Self::Eager(value)
    }
}

impl From<LazySetValues> for LazyObject {
    fn from(value: LazySetValues) -> Self {
        Self::LazySetValues(value)
    }
}

impl std::fmt::Debug for LazyObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Eager(object) => object.fmt(f),
            Self::LazySetValues(iter) => iter.fmt(f),
        }
    }
}

impl LazyObject {
    /// Interprets the [`Self::AxiomaticQueryValues`] variant as an iterator
    /// over the set items and returns an iterator over set items.
    #[inline]
    pub fn set_values(&self, knowledge: &Structure) -> LazySetValues {
        match self {
            Self::LazySetValues(values) => values.clone(),
            Self::Eager(eager) => LazySetValues::ValuesAxiomatically(eager.set_values(knowledge)),
        }
    }

    /// Converts `self` into an object.
    ///
    /// * If `self` was [`LazyObject::Eager`], it just returns that object.
    /// * If `self` was [`LazyObject::LazySetValues`], it collects all
    /// values into a set and returns that.
    pub fn into_object(self) -> Object {
        match self {
            Self::Eager(object) => object,
            Self::LazySetValues(iterator) => iterator.collect_to_set().into(),
        }
    }

    /// Determines if `self` is "truthy", i.e. iff it has at
    /// least one property.
    pub fn is_truthy(&mut self, knowledge: &Structure) -> bool {
        match self {
            LazyObject::Eager(object) => object.is_truthy(knowledge),
            LazyObject::LazySetValues(iter) => iter.next().is_some(),
        }
    }
}

#[derive(Clone)]
pub enum LazySetValues {
    /// Iterator over values of an object.
    ValuesAxiomatically(QueryValuesAxiomatically),

    /// Chains two iterators.
    Union {
        left: Box<Self>,
        right: Box<Self>,
    },

    SubjectsAxiomatically(QuerySubjectsAxiomatically),

    SubjectsAndValuesAxiomatically(QuerySubjectsAndValuesAxiomatically),

    Map {
        knowledge: Structure,
        set: Box<Self>,
        /// This function is captured.
        mapper_function: Object,
    },

    Filter {
        knowledge: Structure,
        set: Box<Self>,
        /// This function is captured.
        filter_function: Object,
    },
}

impl std::fmt::Debug for LazySetValues {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_set()
            .entries(self.clone().map(Property::new_contains))
            .finish()
    }
}

impl LazySetValues {
    pub fn collect_to_set(self) -> Structure {
        let mut properties: Vec<_> = self.map(Property::new_contains).collect();
        Structure::new(&mut properties)
    }

    /// Counts the (remaining) set values of this iterator.
    /// It dedups
    pub fn correct_count(self) -> usize {
        match self {
            LazySetValues::ValuesAxiomatically(axiomatic_query_values) => {
                axiomatic_query_values.count()
            }
            iterator => {
                // This is expensive, no?
                let mut vec = iterator.collect::<Vec<_>>();
                vec.partition_dedup().0.len()
            }
        }
    }
}

impl Iterator for LazySetValues {
    type Item = Object;

    fn next(&mut self) -> Option<Self::Item> {
        match self {
            Self::ValuesAxiomatically(values) => values.next(),
            Self::Union { left, right } => left.next().or_else(|| right.next()),
            Self::SubjectsAxiomatically(subjects) => subjects.next(),
            Self::SubjectsAndValuesAxiomatically(iter) => {
                iter.next().map(|SubjectAndValue { subject, value }| {
                    Structure::new(&mut [
                        Property::new_statement_subject(subject),
                        Property::new_statement_value(value),
                    ])
                    .into()
                })
            }
            Self::Map {
                knowledge,
                set,
                mapper_function,
            } => set.next().map(|item| {
                mapper_function
                    .call(
                        knowledge,
                        array::from_ref(&item),
                        &mut EvaluationContext::default(),
                    )
                    .into_object()
            }),
            Self::Filter {
                knowledge,
                set,
                filter_function,
            } => loop {
                // Eat until some match is found.

                let item = set.next()?;

                if filter_function
                    .call(knowledge, array::from_ref(&item), &mut Default::default())
                    .is_truthy(knowledge)
                {
                    break Some(item);
                }
            },
        }
    }
}
